# Example  .gitlab-ci.yml file
stages:
  - mavenbuild
  - maventest
  - androidbuild
  - androidtest
  - mavenDeploy

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd backend
    - mvn package -B
  only:
    # refs:
    #   - main
    changes:
      - backend/**/*

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd backend
    - mvn test
  artifacts:
    paths:
      - backend/target/*.jar
  only:
    # refs:
    #   - main
    changes:
      - backend/**/*

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./frontend/Scout_App/gradlew
  tags:
   - android_tag
  script:
    - cd frontend/Scout_App
    - ./gradlew build
  artifacts:
    paths:
    - Android_test/app/build/outputs/
  only:
    # refs:
    #   - main
    changes:
      - frontend/Scout_App/**/*

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./frontend/Scout_App/gradlew
  tags:
   - android_tag
  script:
    - cd frontend/Scout_App
    - ./gradlew test
  only:
    # refs:
    #   - main
    changes:
      - frontend/Scout_App/**/*


# Below job builds, deploys, executes jar as service.
autoDeploy:
  stage: mavenDeploy  #do make a stage with same name!
  tags:
   - springboot_tag
  script:
    - cd backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar 
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    # refs:
    #   - main
    changes:
      - backend/**/*


